import {
  ComputerIcon,
  FolderIcon,
  IEIcon,
  NotepadIcon,
  MediaIcon,
  MailIcon,
  ResumeIcon,
  RecycleIcon,
  MinesIcon,
  CalcIcon,
  BirdIcon,
  CardsIcon,
  PlatformerIcon,
  PongIcon,
  BreakoutIcon,
  AsteroidsIcon,
  CityIcon,
  DetectiveIcon,
} from './icons'

export const icons = {
  computer: ComputerIcon,
  folder: FolderIcon,
  ie: IEIcon,
  notepad: NotepadIcon,
  media: MediaIcon,
  mail: MailIcon,
  resume: ResumeIcon,
  recycle: RecycleIcon,
  mines: MinesIcon,
  calc: CalcIcon,
  bird: BirdIcon,
  cards: CardsIcon,
  platformer: PlatformerIcon,
  pong: PongIcon,
  breakout: BreakoutIcon,
  asteroids: AsteroidsIcon,
  city: CityIcon,
  detective: DetectiveIcon,
} as const

export type IconName = keyof typeof icons
